### ISSUE TITLE
Would like people to test my fork which has support for PBP mode + custom VCP codes

### ISSUE THREAD

**Issue by itxchh** [kfix/ddcctl#104]
Implemented PBP mode and it works on my monitor Dell U4320Q.
Also added ability for users to enter a specific VCP code and to modify that value
Would like other people to test - also got instructions on how to implement it for your monitor if it doesn't work.
Fork is here: [https://github.com/itxchh/ddcctl](https://github.com/itxchh/ddcctl)
Instructions in the readme.

Happy to answer any questions

**Comment by rbradcurtis** [comment]
I have this hardware and will test this week.  One suggestion: a handy feature that would complement this change would be the ability to set the various subdisplay inputs when activating PbP mode.

Given the addition of the -vcp, I presume this change shouldn't be too difficult if the appropriate VCP codes can be identified.

As I understand it, there is always the primary input and then up to 3 subdisplays depending on the specific PbP mode.

**Comment by itxchh** [comment]
Yeah there is -php-screen flag which sets the secondary display. But in my monitor unfortunately only have a primary and secondary. But if you identify others let me know and I can easily add them

**Comment by nk9** [comment]
I'd love to be able to control PBP, so I'd like to test… but I'm wary of bricking the monitor with incorrect settings after having read [this bug](https://github.com/kfix/ddcctl/issues/89). I have a Dell U3219Q. Any way I can check before I run your code to see if it's compatible with my hardware?

**Comment by itxchh** [comment]
> I'd love to be able to control PBP from the command line, so I'd like to test… but I'm wary of bricking the monitor with incorrect settings after having read [this bug](https://github.com/kfix/ddcctl/issues/89). I have a Dell U3219Q. Any way I can check before I run your code to see if it's compatible with my hardware?

While of course, I cannot guarantee 100% that the same bug will affect you of course, if you check out my fork, and the [guide on how to find your own pbp value](https://github.com/itxchh/ddcctl#how-to-find-your--pbp-flag). I don't think anything can go wrong. As you will be setting the value to what the monitor sets it to.

**Comment by kfix** [comment]
good luck on your fork @itchx. I'm going to close as this is not a support/discussion forum - I'm afraid I'm going to have to close down issues because of all the randomness being sent in that I don't have time to prune anymore.

I think I'd not agree to integrating a `-pbp` feature as it seems unlikely to be useful across a majority of the monitors with a hardcoded vcp value. I have an (old) LG ultrawide at home that claims to support it so might try it, but even it works my reservation still holds.

 the `-vcp` arg you added looks useful for experimentation, although to add that upstream I think it'll need to flash big bright red letters and prompt before applying, unless a `-force-vcp` is used. We've heard of monitors being broken/bricked from using atypical VCP codes (#58).
