### ISSUE TITLE
-w switch sends "setting VCP control #160"

### ISSUE THREAD

**Issue by lowne** [kfix/ddcctl#12]
Unless I'm missing something, it'd seem it should be filtered out while looping - e.g. around [here](https://github.com/kfix/ddcctl/blob/master/ddcctl.m#L127)

**Comment by kfix** [comment]
Thanks for the report.
The arg parsing is totally fucked.
I'd rather rewrite this in swift than straighten it out...

**Comment by jacobseptember** [comment]
I may have figured this out... I added a simple line `MyLog(@"TEST: control-id = %ld", control_id);`  in front of line 127, and the output when including `-w` is as follows:

> $ ddcctl -d 1 -b 40 -w 40
> 2016-07-05 14:57:26.264 ddcctl[616:19245] D: NSScreen #724048845 (1920x1080) DPI is 92.50
> 2016-07-05 14:57:26.265 ddcctl[616:19245] D: NSScreen #724067022 (1080x1920) DPI is 92.50
> 2016-07-05 14:57:26.265 ddcctl[616:19245] I: found 2 displays
> 2016-07-05 14:57:26.265 ddcctl[616:19245] I: polling display 1's EDID
> 2016-07-05 14:57:26.268 ddcctl[616:19245] I: got edid.serial: 4NVYD4BK0C4L
> 2016-07-05 14:57:26.268 ddcctl[616:19245] I: got edid.name: DELL P2415Q
> 2016-07-05 14:57:26.268 ddcctl[616:19245] D: command arg-pair: d: 1
> 2016-07-05 14:57:26.268 ddcctl[616:19245] TEST: control-id = -1
> 2016-07-05 14:57:26.268 ddcctl[616:19245] D: command arg-pair: b: 40
> 2016-07-05 14:57:26.268 ddcctl[616:19245] TEST: control-id = 16
> 2016-07-05 14:57:26.268 ddcctl[616:19245] D: setting VCP control #16 => 40
> 2016-07-05 14:57:26.378 ddcctl[616:19245] D: command arg-pair: w: 40
> 2016-07-05 14:57:26.378 ddcctl[616:19245] TEST: control-id = 100000
> 2016-07-05 14:57:26.378 ddcctl[616:19245] D: setting VCP control #160 => 40

looks like a simple confusion of whether `-w` has 100000 as its *default value* or its *control_id*. So I changed line 88 to `@-1` instead of `@100000`.

————

This all comes about because I can't seem to use relative brightness control on my P2415Qs. The current brightness is fetched correctly, the target brightness is calculated correctly, and... nothing. Like so:

> 2016-07-05 15:06:59.846 ddcctl[651:33190] D: querying VCP control: #16 =?
> 2016-07-05 15:06:59.947 ddcctl[651:33190] I: VCP control #16 = current: 40, max: 100
> 2016-07-05 15:06:59.947 ddcctl[651:33190] D: relative setting: 40 + 40 = 80
> 2016-07-05 15:07:00.448 ddcctl[651:33190] D: setting VCP control #16 => 80

But the display doesn't actually change brightness. Any thoughts?
