### ISSUE TITLE
Make sleep optional to speed up script for displays that can handle it

### ISSUE THREAD

**Issue by fgimian** [kfix/ddcctl#2]
Hello there, thanks so much for this tool, it works great for me! :smile: 

What I noticed is that it takes around 2 seconds to change a setting and so I started to poke around in the code to see why.

On my screen (BenQ GW2760HS), there seems to be no need for the sleep delay that's added in this line:

```c
                    sleep(1); //stagger comms to these wimpy I2C mcu's
```

My monitor seems to handle it just fine and still updates with this off, but the speed of the app is so much faster.

e.g.

with sleep on

```
real	0m2.153s
user	0m0.011s
sys	0m0.034s
```

with sleep off

```
real	0m0.154s
user	0m0.013s
sys	0m0.034s
```

Would you consider making this optional via a CLI switch for the monitors that can handle it?

Thanks so much!
Fotis

**Comment by kfix** [comment]
I can make the sleep opt-out with a flag or env-var/nsdefault since crashes or failed commands are commonplace without it.






On Sat, Jul 4, 2015 at 4:36 AM -0700, "Fotis Gimian" <notifications@github.com> wrote:
Hello there, thanks so much for this tool, it works great for me! :smile:

What I noticed is that it takes around 2 seconds to change a setting and so I started to poke around in the code to see why.

On my screen (BenQ GW2760HS), there seems to be no need for the sleep delay that's added in this line:

```c
                    sleep(1); //stagger comms to these wimpy I2C mcu's
```

My monitor seems to handle it just fine and still updates with this off, but the speed of the app is so much faster.

e.g.

with sleep on

```
real    0m2.153s
user    0m0.011s
sys     0m0.034s
```

with sleep off

```
real    0m0.154s
user    0m0.013s
sys     0m0.034s
```

Would you consider making this optional via a CLI switch for the monitors that can handle it?

Thanks so much!
Fotis

---
Reply to this email directly or view it on GitHub:
https://github.com/kfix/ddcctl/issues/2

**Comment by fgimian** [comment]
Is it possible to allow the sleep time to be set in milliseconds via the CLI?  I think that would be the most powerful and flexible option.  By default, it could be 1000 ms (1 second) as it is now, and then people can lower or raise it as required.

Thanks again for your awesome tool!
Fotis

**Comment by fgimian** [comment]
Thank you so much! :smile:
