### ISSUE TITLE
Put compiled binary in Releases? 

### ISSUE THREAD

**Issue by sn0wyfall** [kfix/ddcctl#72]
Is there any way someone can provide the compiled binary for this? I really don't want to go through the hassle of download Xcode, figuring out how to compile this, etc.

**Comment by marnovo** [comment]
Compiled all three amd/intel/nvidia from the latest commit https://github.com/kfix/ddcctl/commit/02dcf6c9ae77783f50a9948a829dee6865131ef6 using Xcode CLT 12 beta 5: [ddcctl-02dcf6c-allbin.zip](https://github.com/kfix/ddcctl/files/5135383/ddcctl-02dcf6c-allbin.zip)

**Comment by sn0wyfall** [comment]
Thanks! I totally agree. I was just thinking maybe it'd be easier for people like me who don't want to download Xcode, but for all of those other people who want to compile it from source they can do that.

**Comment by kfix** [comment]
Sorry, but I am too swamped with work to get around to this.

It'd be great to have CI/CD wired up for this project, which could feed binaries into the Releases tab.
Amazingly, it looks like GH Actions provides  a basic macOS builder:
https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

It seems quite a few folks use this, much more than I do (because of Night Shift) so they deserve that much.

I doubt it could functionally test, since no monitors in the cloud, but could at least ensure things are compiling and runnable.

**Comment by kfix** [comment]
Basic releases pipeline is up now.
